### ISSUE TITLE
Native instance lock when using Postgres

### ISSUE THREAD

**Issue by joostjager** [lightning/bolts#1023]
With bbolt, it isn't possible to run two lnd instances using the same database simultaneously. Bbolt is protecting against that. WIth postgres however, there is no such mechanism in place by default. Running two instances with postgres in parallel could have bad consequences.

In a k8s setup, this could happen more easily than one would think. Rolling deployments for example bring up the new instance before terminating the old one.

Leader election is the current solution that lnd offers, but it requires an etcd instance. See also https://github.com/lightningnetwork/lnd/issues/6887

An alternative could be to use a postgres-based lock using for example https://github.com/cirello-io/pglock.

**Comment by tnull** [comment]
I believe you intended to open this in the LND repo?

**Comment by joostjager** [comment]
Ah yes, indeed. Thanks
