### ISSUE TITLE
Make lighting address easier to recognize, easier to read, easier to remember

### ISSUE THREAD

**Issue by OliverThompsonOT** [lightning/bolts#1091]
Support Sats Names to make lighting address easier to recognize, easier to read, easier to remember

If you don't know what is Sats Names, you can read this doc:
https://docs.sats.id/sats-names/about

**Sats Names is a standard for writing names to Bitcoin using ordinals. 
The goal is to build a name ecosystem for Bitcoin, that is built by Bitcoiners, and developed entirely on Bitcoin.**

**it can make lighting address easier to recognize, easier to read, easier to remember, and most important, it's decentralized.**

All namestate lives on Bitcoin
The protocol will remain credibly neutral
Names are inscribed as ordinals, and **the only fees involved are paid to miners on the Bitcoin network.**
FAQs: https://docs.sats.id/sats-names/faqs

### Why we need this?

easier to recognize, easier to read, easier to remember, and most important, it's decentralized
It seems that some Lightning Network wallets are currently using email as an address scheme, but this solution is not decentralized, it's not neutral enough

### how to do it?

Firstly, users can inscribe (mint) a valid inscription on Ordinals like this json:

`
"p": "sns", 
"op": "reg", 
"name": "test.sats", 
"lighting-invoice": "*******", 
"BTC": "bc1p*******"
`

then as a wallet, wallet can index these inscription, so they can know which invoice a sats name points to.

so, when a user use lighting wallet, they click "send" button, and input test.sats, then wallet can know which invoice test.sats points to. then wallet can send bitcoin(sats) to this invoce.

also, there are many rules about what is valid inscription, you can see this doc: https://docs.sats.id/

**Comment by t-bast** [comment]
Closing for the same reason as #1084
