### ISSUE TITLE
More funds were locked, than the channel itself after force close. 

### ISSUE THREAD

**Issue by ybaidiuk** [lightning/bolts#1112]
I did force close but still can not figure out some logic. 
https://mempool.space/address/bc1qnj29s89v67pa4cepffcalx8kcy5kzgrdhnpqvrryh895a42gefts5d87cm

Did chart for better visualization
![image](https://github.com/lightning/bolts/assets/11969255/1ebfb2cf-c6b3-4f3a-82d2-03732898ca81)
![image](https://github.com/lightning/bolts/assets/11969255/a2df984a-0262-48e3-8fcb-c854ae23e23e)
have 3 question for advanced developers, because I can not figure it out 2 days already. 

1. Why was touched my sats (...ccl3 address), which was not attached to this channel at all? now because of 20k sats i get locked 500k for 2 weeks... 
2. Why lock time 539184385 point on 1987 year?
3. How I can claim  later sats from ...mptr address? 

Please help me figure out if it okay or some potential bug with LND.

**Comment by t-bast** [comment]
This isn't the right place for this issue, this is the specifications repository.
I believe you want to open this in https://github.com/lightningnetwork/lnd
