### ISSUE TITLE
[feature] Allow the recovering of (outgoing) HTLCs in a DLP case.

### ISSUE THREAD

**Issue by ziggie1984** [lightning/bolts#1137]
Currently when having a data loss we are still able to recover our amount of funds from the remote commitment transaction using the DLP protocol. However when there are outgoing HTLCs on the Commitment we are currently not able to recover those although it would be easily possible if the remote peer would provide us data so that we would reconstruct the `witnessScript` of the ougoing HTLC output on the remote commitment transaction.

Maybe we could just add additional data to the `channel_reestablish ` msg:

 HTLC:

Needed to reconstruct the witness script of the HTLC on the remote commitment:
- Hash
- Absolute Timelock of the HTLC (could be grinded but why not provided it when we are at it?)
- CommitmentPoint (already provided in the `channel_reestablish` msg.

**Comment by t-bast** [comment]
Yes, encrypted peer backups are way superior because you can fully resume a channel without even needing to close it. This has been used in production for almost 3 years for Phoenix, I highly recommend implementing this!

**Comment by ziggie1984** [comment]
Sounds good, closing in favour of https://github.com/lightning/bolts/pull/1110
