### ISSUE TITLE
to_self_delay cannot be updated after opening a channel

### ISSUE THREAD

**Issue by AndySchroder** [lightning/bolts#1144]
As far as I can tell, the `to_self_delay` cannot be updated after opening a channel. Can it? With dynamic fee markets I think the two parties in a channel should be able to agree to update the `to_self_delay` with a new commitment transaction at any time. Is there any technical reason why this cannot be possible, or is there just no communication protocol for doing it yet?

**Comment by saubyk** [comment]
Can be addressed with dynamic commitments?
https://github.com/lightning/bolts/pull/1117

**Comment by t-bast** [comment]
> is there just no communication protocol for doing it yet?

That's exactly why, and also because it's not a very high priority feature (`to_self_delay` is only used when force-closing, which shouldn't happen anyway). This can be done during a splice, or with any other "dynamic commitments upgrade" protocol.

**Comment by AndySchroder** [comment]
Looks like https://github.com/lightning/bolts/blob/3aacdb186b15942218dd860252e953db3e1cd258/ext-dynamic-commitments.md#channel-opening-parameters does mention `to_self_delay`.
