### ISSUE TITLE
Comments on the Lightning Dev Summit roasbeef’s notes

### ISSUE THREAD

**Issue by ariard** [lightning/bolts#1204]
https://docs.google.com/document/d/1erQfnZjjfRBSSwo_QWiKiCZP5UQ-MR53ZWs4zIAVcqs/edit?usp=sharing

> Replacement cycling protection 
> Anti-cycle repo: https://github.com/instagibbs/anticycle  
> Client side protection against pinning stuff 
> Uses zmq etc to detect spurious state transitions 

Become a bandwidth / CPU DoS vector, see https://github.com/bitcoin/bitcoin/issues/28699 for more.
A replacement cycling attacker can just adapt its broadcasting to the public spurious state transition heuristics in anticycle.py.
And I’m not even considering conflicting the mempool(s) of the defender to falsify the heuristics.

> Super scalar 
> Components 
> Decker wattenhofer 
> Supports N Parties 
> Has a set amount of state changes, based on decrementing lock times 
> Closing 

Broken, as there is an inflated on-chain weight unit cost for the worst-case of the subtree of transactions.
This does not make the problem of fee management better, as even the LSP has to over-capitalize and it’s bounded by `MAX_MONEY`.
The private key handover to fee-bump makes the whole scheme trusted for the lightning user, a LSP can steal fund. See Delving bitcoin comments for more.

> Is there some impossibility result associated with the ability to the join off-chain?

I don’t have math proof, though it’s probably back to solving the double-spend problem.
A Nth participant of an off-chain construction cannot be sure that N-1 participants are showing the correct off-chain state, without validating the issuance of the off-chain states back to the root in the chain.

(I remember  we try to solve with Gleb the “_Last Mile Mobile Onboarding problem_", mobile or not one day at the restaurant in pre-war times Kiev, though we never figure out a smart way to do it in the state of today consensus rules…).

**Comment by Roasbeef** [comment]
[Discussions](https://github.com/lightning/bolts/discussions) were enabled on the repo a few weeks ago, I think that would be a better place (or delving) to post comments. This is an issue tracker related to concrete aspects of the spec itself.
