### ISSUE TITLE
BOLT2: Clarification regarding outstanding HTLCs, `max_htlc_value_in_flight_msat`

### ISSUE THREAD

**Issue by C-Otto** [lightning/bolts#422]
After reading about `open_channel`, I still do not understand what the `max_htlc_value_in_flight_msat` is used for, and what outstanding HTLCs are. Is it possible to initiate several payments in parallel (in the same channel)? Isn't `funding_satoshis` a useful limit (minus fees and such)?

**Comment by C-Otto** [comment]
I just had a chat with @cdecker and now understand the concept. I suggest to explain the concept in the motivation section in BOLT2.

**Comment by rustyrussell** [comment]
We do define it, but perhaps we can make it clearer?

```patch
-`max_htlc_value_in_flight_msat` is a cap on total value of outstanding
-HTLCs, which allows a node to limit its exposure to HTLCs; similarly,
+`max_htlc_value_in_flight_msat` is a cap on total value of concurrent
+unresolved payments, which allows a node to limit its exposure to HTLCs; similarly,
 `max_accepted_htlcs` limits the number of outstanding HTLCs the other
 node can offer.
```

**Comment by C-Otto** [comment]
That is better, yes!

**Comment by t-bast** [comment]
Closing this stale issue.
