### ISSUE TITLE
goodbye

### ISSUE THREAD

**Issue by robtex** [lightning/bolts#464]
I really really miss a goodbye-message or a general free-text error/info message. Can we make one please?
I'm getting a bit frustrated with peers hanging up on me without telling my why. It's not civilized and i am deeply offended!
Did they just restart their node or was it something I said? Did they run out of memory or did I send a message that wasn't signed properly? Did I talk too much too quickly? Did I forget to answer the ping? At least I don't get a message 17 but I can't say i've ever seen one.

**Comment by rustyrussell** [comment]
@Roasbeef usually says that c-lightning gives errors on any violation at all :)

**Comment by t-bast** [comment]
Implementations can now use the `warning` message if they want to say goodbye to their peers. The spec will not mandate implementations to do it though.
