### ISSUE TITLE
channel_disabled flags

### ISSUE THREAD

**Issue by TheBlueMatt** [lightning/bolts#791]
The channel_disabled HTLC failure reason has two flags bytes in BOLT 4, but there is no reference to what they should be or motivation as to why they are there. I presume its intended to be able to say why the channel is disabled, but would be nice to spell that out.

**Comment by t-bast** [comment]
Agreed, this is under-specified.
It only says that those should reflect the channel "settings", which is unclear.
In eclair we set the first byte to `message_flags` (from `channel_update`) and the second one to `channel_flags` (from `open_channel`).

**Comment by TheBlueMatt** [comment]
Huh, interesting - at least for `message_flags` it should be redundant because a `channel_update` is included, no? As of the linked PR there we now set both bytes to 0.

**Comment by t-bast** [comment]
You're right, they're even both completely redundant as they are in the `channel_update`!
We don't use this information at all when *receiving* such an error, I'm also curious to understand what was the original reason for the structure of this error...

**Comment by t-bast** [comment]
@rustyrussell @Roasbeef do you remember the rationale behind those? Are they interpreted/useful for c-lightning/lnd?

**Comment by Roasbeef** [comment]
IIRC they were initially a single set of bytes, but then we split them when we re-org'd feature bits in general?

**Comment by rustyrussell** [comment]
It was added in c60e5e05eccb2cc4da0bc18ca955f61c6213931f by @pm47 

Looks like there was some confusion, and it was missed in the melee:

https://github.com/lightningnetwork/lightning-rfc/pull/167

Hilariously, it seems like the extra space in "[\`u16\`: \`flags\`]" means that it doesn't match the output in tools/extract-formats.py and so we don't actually generate any fields for this error message.  This is why c-lightning doesn't include any fields when it sends  a "channel_disabled" message...
