### ISSUE TITLE
Disable Channel for forwarding on user configurable liquidity level to avoid failed forwarding events.

### ISSUE THREAD

**Issue by BhaagBoseDK** [lightning/bolts#899]
As the lightning network is growing, the number of "TemporaryChannelFailure" while evaluating routing path is increasing exponentially and have the potential to choke the network.

These errors primarily occur due to lack of liquidity on the forwarding channel at the node. There are several work around available to avoid this situation, namely increasing fees, increasing base fee, automatic rebalancing etc however a protocol level solution would kill at issue at the root and will prevent numerous routing failure attempts before a successful route is found.

[lnd grpc API already provides for enabling and disabling channel message](https://api.lightning.community/#v2-router-updatechanstatus) and some implementations use these to disable channel when liquidity is low and re-enable the channel with liquidity is replenished. This helps in avoiding forwarding failures. 

At lnd protocol level, a change could be introduced to disable a channel at user configurable liquidity level (default 5%)

This configuration can be changed in lnd.conf if needs to be adjusted. Setting to 0 would disable this feature.

lnd.conf
disable_channel_threshold = 0.05

If enabled, as soon as channel local liquidity falls below the disable_channel_threshold, the channel will be disabled for forwarding (but can still receive incoming).

Once the local liquidity is above disable_channel_threshold, the channel will be enabled again.

This implementation would save a lot of issues in trying to find routing path through depleted channels.

**Comment by btcontract** [comment]
> This implementation would save a lot of issues in trying to find routing path through depleted channels.

It most likely won't: channel balance changes can be very dynamic and especially for busy channels chances are that by the time most nodes receive `disabled` update a channel itself is able to route again, and vice versa.

This also has a significant downside which is elevated gossip traffic and increased number of so called flapping channels.

**Comment by BhaagBoseDK** [comment]
1- heuristically flapping channels do not happen around the depleted levels. 
2- most channel balances are pretty static - they do not go from 5% -> 95% 100s of times a day but the same 5% channel fails 1000s of times a day.
3- gossip updates can be controlled by high/low watermark level
disable_channel_threshold = 0.05
enable_channel_threshold = disable channel_threshold + 0.05

Further, a hard limit can be placed on disable_channel_threshold (say 0.2) further reducing the flipping channel issue.

BTW, most node owners are implementing work around today using fee updates (which generates an equally higher amount of gossip if not more).

**Comment by t-bast** [comment]
I don't understand why you would raise this issue to the spec, this is purely an implementation choice.

The spec will not define a threshold below which all implementations should consider a channel unbalanced as this is completely arbitrary and opinions will vary greatly on what threshold (if any) should be used.

**Comment by BhaagBoseDK** [comment]
wouldn't it be part of the specification to address "TemporayChannelFailure" which chokes the network today?

I am happy to create an implementation issue if required if you let me know where it fits the best?

**Comment by dlaptev** [comment]
I agree with Bastien that the details should be left to the clients. But I still think that the general idea deserves the discussion on the protocol level: "if a channel is unlikely to route due to liquidity issues - should disable". This will greatly benefit the network as a whole if it becomes the default behavior in all the implementations, not one.

**Comment by Roasbeef** [comment]
Closing as this is purely an implementation level issue. The protocol level functionality to disable a channel can be scripted by an implementation's API to implement the desired functionality.
