### ISSUE TITLE
BOLT01 example of `init` message incorrect?

### ISSUE THREAD

**Issue by instagibbs** [lightning/bolts#937]
> 0x00100000000001012a030104: the extension contains two odd TLV records (with types 0x01 and 0x03)

IIUC, `0x01` is `networks`, a known even feature which requires a multiple of 32-byte as a data payload("...*chain_hash"), and this example has single byte lengths for each type. This should cause it to be invalid?

**Comment by t-bast** [comment]
You're right, these test vectors were made before we added the `networks` tlv field to the `init` message.
My bad, I should have made this more future-proof by using tlvs in a much higher range, I'll fix that.
Thanks for the report!

**Comment by instagibbs** [comment]
I could also submit a patch if it's not too much trouble

**Comment by t-bast** [comment]
Great, that would be nice, I'll let you update this one, thanks!
