### ISSUE TITLE
bolt 2: coop-closing clarification

### ISSUE THREAD

**Issue by Crypt-iQ** [lightning/bolts#964]
I am confused with the sending node requirements [here](https://github.com/lightning/bolts/blob/master/02-peer-protocol.md#requirements-5) at the bullet point "if there are updates pending on the receiving node's commitment transaction". The general overview under number [1](https://github.com/lightning/bolts/blob/master/02-peer-protocol.md#channel-close) and diagram lead me to believe that sending `shutdown` with _committed_ HTLC's is fine. So I think the referenced bullet point above is referring to _uncommitted_ updates instead. If so, does this count HTLC's where we _owe_ signatures to the remote party?

```
A                B
   <--add--
   <--sig---
   ---rev-->
   ---shutdown-->
   // allowed even though the add may be considered a "pending" update depending on your terminology?
```

My second point of confusion involves both the sending node and the receiving node requirements. The sending node "SHOULD fail to route any HTLC added after it has sent shutdown". Here I am assuming that this is when the sending node is _receiving_ HTLC's from the counter-party as the sender routing through the channel they just sent a shutdown on would be a spec-violation. The receiving node "once there are no outstanding updates on the peer, UNLESS it has already sent a shutdown... MUST reply to a shutdown message with a shutdown". These two requirements seem to be at odds with one another, let's assume A & B start on a clean commitment state:
```
A                        B
   --shutdown-->
   <-----add----
```
Let's say that B received the shutdown message and _then_ sent the add. While it is a spec violation (as B should have sent shutdown), A is unable to do anything here. It could be the case that B sent the add before receiving the shutdown message, and A has already sent the shutdown message. My question boils down to this: _when_ does it become appropriate for A to enforce that B sends a shutdown if there is a clean channel state, rather than sending more HTLC's? If the answer is never, then the "MUST reply to a shutdown message with a shutdown" could use wording instead of "MUST".

**Comment by t-bast** [comment]
I can detail how eclair behaves in those cases, and how I interpret the spec (there may be mistakes, which would be my own).
Our behavior is to not send our own `shutdown` while we have added htlcs or fee updates that we haven't signed yet (the "pending updates" we consider here are actually only `update_add_htlc` and `update_fee`).
We expect our peer to do the same, otherwise we force-close.

So this would be valid:

```
    A                B
      -----add----->
      -----sig----->
      ---shutdown-->
```

But this would not:

```
    A                B
      -----add----->
      ---shutdown-->
      -----sig----->
```

Regarding your specific examples, they are both valid from my point of view.

**Comment by Crypt-iQ** [comment]
What does c-lightning / LDK do here? @rustyrussell @TheBlueMatt

**Comment by Roasbeef** [comment]
We need to confirm on the lnd side (if we count update_fee), but it seems the middle ground here spec wise is to _only_ send the shutdown message once the commitment is fully clear (including update_fee messages). If you receive one early, then you should just wait until the coast is clear to enter the second stage of co-op close negotiation.

**Comment by TheBlueMatt** [comment]
SGTM, I believe LDK currently only considers update_add as the "pending updates" criteria here, but it seems like the correct way forward is to not verify that on receiving shutdown, but to include update_add/update_remove/update_fee all as things that block sending shutdown.

**Comment by niftynei** [comment]
clightning only sends shutdown after a commit has been sent + reconnect, so there's never any pending updates.

**Comment by Crypt-iQ** [comment]
> not verify that on receiving shutdown

I'm confused - what does this mean?

Also, I don't think the bolt specifies what should be done if a shutdown is received and there are pending updates?

**Comment by TheBlueMatt** [comment]
> Also, I don't think the bolt specifies what should be done if a shutdown is received and there are pending updates?

Yes, my point is the way forward for all of us is probably to not verify anything about "pending updates" when receiving shutdown, but be conservative and only send shutdown if *nothing* is pending.

**Comment by Crypt-iQ** [comment]
> Yes, my point is the way forward for all of us is probably to not verify anything about "pending updates" when receiving shutdown, but be conservative and only send shutdown if nothing is pending.

Ok that sounds fine to me.

It's not spelled out currently in the spec for shutdown (for closing_signed it is), but if shutdown has been exchanged and the connection goes down before reaching the closing_signed stage, should startup erase that shutdown "state", making the channel fully operational again? It would be easier on lnd's side to avoid any persistence there

**Comment by Crypt-iQ** [comment]
Should the spec only allow closing_signed if there's no pending commitment? It could be the case that the non-pending remote commitment has an htlc and neither the local commitment or the remote pending does. It could also be the case that the pending commitment is at a different feerate

**Comment by Roasbeef** [comment]
> It's not spelled out currently in the spec for shutdown (for closing_signed it is), but if shutdown has been exchanged and the connection goes down before reaching the closing_signed stage, should startup erase that shutdown "state", making the channel fully operational again? It would be easier on lnd's side to avoid any persistence there

Turns out the spec has a section on this, brought up by bluematt: 
```
[](https://github.com/lightning/bolts/blob/master/02-peer-protocol.md#rationale-11)upon reconnection:
if it has sent a previous shutdown:
MUST retransmit shutdown.
```

**Comment by Roasbeef** [comment]
Final lingering thing here seems to be:

  1.  Should you allow `update_fee` after shutdown has been sent but you still have HTLCs? 
  2. Can you send a closing signed when you have a pending commitment?

Answer seems to be yes for 1, as long as there're no HTLCs. 

#2 needs some more investigation.

**Comment by vincenzopalazzo** [comment]
>Should you allow update_fee after shutdown has been sent but you still have HTLCs?

Maybe I'm missing some things, but what is the goal to accept a update_fee after a `shutdown`? The negotiation of the fee, it is some things that can be done before sending the shutdown?

I'm a little bit confused on how this update can happens

**Comment by TheBlueMatt** [comment]
> Maybe I'm missing some things, but what is the goal to accept a update_fee after a shutdown?

Once we've sent the `shutdown` message, we may still have quite some time before our HTLCs resolve (some timeouts are a week+). During that time, the prevailing network feerates may change enough that we want to update the channel fee, because ultimately we still need the ability to broadcast the latest channel state and hit the chain if something goes wrong.

**Comment by vincenzopalazzo** [comment]
>(some timeouts are a week+)

Resolved my problem, thanks for the clarification
