### ISSUE TITLE
[Logic Nit] Description of Commitment Transaction Outputs and the to_self_delay

### ISSUE THREAD

**Issue by ziggie1984** [lightning/bolts#975]
In the bolt in says:

> To allow an opportunity for penalty transactions, in case of a revoked commitment transaction, all outputs that return funds to the owner of the commitment transaction (a.k.a. the "local node") must be delayed for `to_self_delay` blocks. This delay is done in a second-stage HTLC transaction (HTLC-success for HTLCs accepted by the local node, HTLC-timeout for HTLCs offered by the local node).

In my opinion the second part of the sentence is not correct bc the `to_self_delay`is only constructed in a second-stage HTLC transaction for HTLCs, but there is still the `to_local` output which has a `to_self_delay` without any second stage.

Therefore I suggest changing the sentence to something like this:

For HTLC outputs this delay is done in a second-stage HTLC transaction (HTLC-success for HTLCs accepted by the local node, HTLC-timeout for HTLCs offered by the local node).

**Comment by ziggie1984** [comment]
Feel free to close if it over complicates things :)

**Comment by TheBlueMatt** [comment]
Sure, feel free to open a PR that adds a "For HTLCs," at the start or similar.

**Comment by t-bast** [comment]
Fixed by #983
